trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  frontendFolder: 'frontend'
  backendFolder: 'backend'
  buildArtifactStagingDirectory: '$(Build.ArtifactStagingDirectory)'

steps:
# Setup Node.js
- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: 'Install Node.js'

# Install & Build Backend
- script: |
    cd $(backendFolder)
    npm install
    npm run build || echo "No backend build step"
  displayName: 'Build Backend'

# Archive Backend
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(backendFolder)'
    Contents: '**'
    TargetFolder: '$(buildArtifactStagingDirectory)/backend'

# Install & Build Frontend
- script: |
    cd $(frontendFolder)
    npm install
    npm run build
  displayName: 'Build Frontend'

# Archive Frontend
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(frontendFolder)/build'
    Contents: '**'
    TargetFolder: '$(buildArtifactStagingDirectory)/frontend'

# Publish Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(buildArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
