trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  backendDir: 'backend'
  frontendDir: 'frontend'
  buildOutput: '$(Build.ArtifactStagingDirectory)'

steps:
- task: UseNode@1
  inputs:
    version: '18.x'
  displayName: 'Install Node.js'

# Install & Build Backend
- script: |
    cd $(backendDir)
    npm install
    echo "Backend build skipped (none defined)"
  displayName: 'Build Backend'

# Copy backend to artifacts
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(backendDir)'
    Contents: '**'
    TargetFolder: '$(buildOutput)/backend'

# Install & Build Frontend
- script: |
    cd $(frontendDir)
    npm install
    npm run build
  displayName: 'Build Frontend'

# Copy frontend build output
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(frontendDir)/build'
    Contents: '**'
    TargetFolder: '$(buildOutput)/frontend'

# Publish artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(buildOutput)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
